mysite/ecommerce/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required 
from . import views

app_name="ecommerce"


urlpatterns = [
    path('', login_required(views.home), name = 'home'),
    path('my_tickets/', login_required(views.order_list), name='order_list'),
    path('logout/', views.logout, name = 'logout'),
    
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('ecommerce.urls', namespace='ecommerce')),
    path('user/', include('users.urls', namespace='user')),

]

mysite/users/urls.py
from django.urls import path

from . import views
app_name="users"

urlpatterns = [
    path('registration/', views.registration, name = 'registration'),
    path('login/', views.login, name = 'login'),
    
    
]

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>site</title>
    </head>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
            

    <body>
        <nav>
            <div class="nav-wrapper">
                {% if user.is_authenticated %}
                <a class="right">გამარჯობა {{ request.user.username }}</a>
                {% endif %}
              <ul id="nav-mobile" class="left hide-on-med-and-down">
                {% if user.is_authenticated %}
                <li><a href="{% url 'ecommerce:order_list' %}">ჩემი ბილეთები</a></li>
                <li><a href="{% url 'ecommerce:home' %}">მთავარი გვერდი</a></li>
                <li><a href="{% url 'ecommerce:logout' %}">გამოსვლა</a></li>
                {% else %}
                <li><a href="{% url 'user:login' %}">ავტორიზაცია</a></li>
                <li><a href="{% url 'user:registration' %}">რეგისტრაცია</a></li>
                {% endif %}

              </ul>
            </div>
        </nav>

        {% block content %}{% endblock %}
        
    </body>
    <script>
        document.addEventListener('DOMContentLoaded', function() {
        var elems = document.querySelectorAll('select');
        var instances = M.FormSelect.init(elems);
        });
    </script>
</html>